### ISSUE TITLE
[Feature]: Option to swap item and shulker icons

### ISSUE THREAD

**Issue by vlad2305m** [BVengo/simple-shulker-preview#12]
### Request Description

I would like to see the item in the slot, and shulker as the amount

**Comment by BVengo** [comment]
Thanks for the suggestion :) Just to clarify, this would be toggle-able if implemented.

I think I'll pass on this functionality for now, although if someone finds a clean implementation then I won't turn down their contributions. My thoughts are mostly along the lines of:
- Seems like it will take a lot of work for very little gain (for the majority)
- Will produce some weird inconsistencies in where items are rendered. When a shulker is empty then it would be rendered normally, which would be inconsistent with all the other shulker slots. Although it may feel okay in the end, dealing with that sort of inconsistency will be a pain to code (hence point 1).
- Will be a bit confusing with the existing support for recursive shulkers. This is the least important point though,  because it won't affect the majority and the setting would be toggleable.

**Comment by vlad2305m** [comment]
See #11. I kindof merged them together after a bit of thinkig.

**Comment by vlad2305m** [comment]
#14

**Comment by vlad2305m** [comment]
You may consider adding a separate category with offsets organised in expandable sections

**Comment by vlad2305m** [comment]
![Screenshot_20230415_144517](https://user-images.githubusercontent.com/43315575/232224478-8cb8f45e-c80c-4b48-9649-4a21e4e229c3.png)

**Comment by BVengo** [comment]
Hi vlad,
Thanks again for this suggestion. I'm going to close this issue for now, but we'll see if more interest rises in the future.
