### ISSUE TITLE
[Bug]: Two small bugs on 1.20.1

### ISSUE THREAD

**Issue by sternschnaube** [BVengo/simple-shulker-preview#19]
### Describe the Bug

# 1 - If you stack two or more Shulker Boxes, the icon is overlapping.
![image](https://github.com/BVengo/simple-shulker-preview/assets/120551916/b9ec7879-2756-4436-8cf0-8e0b243c84c3)

# 2 - Example, if you take a stack from your inventory, right clicking the items one by one into a different slot in your inventory. You see this item flickering on the first Shulker Box in the row.
![image](https://github.com/BVengo/simple-shulker-preview/assets/120551916/ece98016-150d-4dc5-b799-b3c403420315)

### Steps to Reproduce

/

### Expected Behavior

/

### Fabric Version

0.14.21

### Mod Version

Latest Port to 1.20

**Comment by BVengo** [comment]
Thanks for reporting this - I'll be looking further into it prior to the 1.20.1 version release..

**Comment by BVengo** [comment]
Hi again :)
Which mods are you using in example 1? I tested against both tweakaroo and shulkerboxtooltip yet neither had the overlap issue. Could you please also check if decreasing your z position helps, because if it's too high it will overlap with tooltips.

I can't seem to replicate example 2 at all. Could you please test with other mods disabled to see if there is any interference?

**Comment by sternschnaube** [comment]
I really like the new "Show Capacity" Feature.
Could you make it please possible to display this bar on top, or even to the sides?
And a option to disabling it for stacked shulkers would be great - since they are full.

I was trying now to lower my Z value.
Normal shulkers are 6 now, and stacked ones 5.
It seems that the second bug is gone now.

But the first is still there, I will check which mod is creating this issue.

**Comment by BVengo** [comment]
Glad to hear you enjoy it! As you can see, I've added the capacity controls as a future feature because it's a pretty smart idea (and consistent with the rest of the mod).

Could you open a new issue for the stacked shulkers with a bit more detail? I'd like to keep all the feature requests seperated out for further discussion.

Finally, glad to hear your 2nd issue seems to be resolved now. I'll keep an eye out for your updates on the 1st one.
Could you please also clarify what you mean by 'stacked shulkers'? I just want to confirm that we're on the same page for debugging this particular issue.

**Comment by sternschnaube** [comment]
It's nicee to have this indicator, but it makes for me no sense for stacked shulkers.
Since the stacked shulker ones are always full.
(17 stacked shulkers with sand)

Maybe another option to change the indicator color blue to something else.
And being able to select a different color if a shulker is full / or you can disable it entirely.

![image](https://github.com/BVengo/simple-shulker-preview/assets/120551916/04ba4720-dcdd-4879-b2e5-b21ef3c0b612)

I think we can close this and after I found out which mod is creating this issue, I open a new case for this.
(The overlapping icon)

**Comment by BVengo** [comment]
I've now added an extra capacity control to the new issue to deal with that in the future.

I'll keep this issue open for troubleshooting your bug though, no need to create new ones.

**Comment by BVengo** [comment]
Closing now - I would have expected a couple more comments after the 1.20.1 release but I think we're all in the clear.

**Comment by sternschnaube** [comment]
Found not the time to looking further into it. I will come again to it when I spot the issue.
