### ISSUE TITLE
[Dum question] how set custom icon

### ISSUE THREAD

**Issue by WolfgamingWG** [BVengo/simple-shulker-preview#25]
### Describe the Bug

Am sorry for dumb question but I am very new to this mod and I've  not been able to find a way to set a custom icon to shulkers, I can't find a description on it either, not on modrinth, github nor curseforge. Can someone please explain, thank you alot and sorry for dumb question.

Also maybe handy to add the how to on the pages so others won't have to go trough the same struggle. :)

### Steps to Reproduce

N/A

### Expected Behavior

N/A

### Mod Version

Latest

**Comment by BVengo** [comment]
Hi there! No worries at all, no dumb questions here :) 

I do have documentation for the mod settings on each of those pages, but they're not as verbose as they used to be since I added more settings. I think I'll make it a future goal to have all the settings properly listed at the very least on GitHub.

The answer to your question depends on what you mean by 'custom'. This mod doesn't support displaying your own custom images in the game, but instead displays an icon based on the contents of your shulker boxes. 

You may have seen that one of the dependencies of this mod is [ModMenu](https://modrinth.com/mod/modmenu). It provides you with a list of all the mods you have installed and, if you hover over the mod, you'll see a config button appear that takes you to the mod settings screen.

In the settings for Simple Shulker Preview, there's an option to adjust your display items based on some pre-set options.
- First: Displays the first item to appear (not necessarily the first slot!). This is the default option.
- Last: Displays the last item to appear
- Most: Displays whichever item you have the most of
- Least: Displays whichever item you have the least of
- Unique: Only displays an icon if all items are the same

There are also various other options for:
- Setting a minimum item limit (e.g. you could set it to only display an icon if the box is full)
- Display options (where the icon is located)
- Compatibility options (enabling compatibility with other mods or experimental items)

I hope this helped!

**Comment by WolfgamingWG** [comment]
Ah yeh that answers my question, I was thinking of asigning a item that is in the game to a shulker even when nothing is in the shulker, can this be turned into a suggestion if possible? 

I would love to see this mod be able to display an item of choosing on the shulker regardless of what is in the shulker. Let's say I have a shulkerbox for end items, I want an enderpearl as icon but not necessarily keep enderpearls in said shulker. 

A great example can be the mod called "Quick menu", a mod that allows quick chat msgs/commands that allows to pick a custom item for icon, if implementing a custom icon like that is possible I would love to see it added.

**Comment by BVengo** [comment]
Closing this as completed, thanks to the initial work by @Boden-C and then the overhaul of the mod I had to do for 1.20.5.

You can now name your shulker in the typical `minecraft:grass_block` convention to assign a permanent icon to it, even when empty. Helpfully, the anvil will show the new icon as soon as you've typed it correctly, so you won't waste any XP on incorrect names.

**Comment by Boden-C** [comment]
> You can now name your shulker in the typical `minecraft:grass_block` convention to assign a permanent icon to it

If you used my code, it should match anything any custom name that contains all the words in the id

Specifically, it looks for the id that has the most amount of matches in the custom name other than "shulker" and "bundle" so

Allowable
`Grass Block`
`Shulker of Grass Block`
`Grass Block Shulker Box`

NOT Allowable
`Grass` - couldn't get this functionality as it would match `Cobblestone` in `Cobblestone Stairs`
`Wood` - maybe you can add functionality for that but I didn't check any "categories"

**Comment by BVengo** [comment]
Locking since the original question has been handled. For discussion around implementation, please see #28
