### ISSUE TITLE
[Feature]: Placed shulkers preview frames

### ISSUE THREAD

**Issue by Reava** [BVengo/simple-shulker-preview#26]
### Request Description

hello there

Like the way preview icons are in inventory, if there could be a preview icon of what's most in the shulker outside of the shulker when placed (say on the top part) as if there was an item frame with that item placed, this would speed up finding which shulker is when working with a large number of shulkers placed and collaborating ^^

I dont know how feasible that is, and to be honest, this is something i saw from another mod (Shulker+) but their implementation was.... inefficient and impractical (using anvils and items to hard set it instead of auto assign based on content...)

But needless to say, this is still something i'd love to see, ^^
Thank you for the amazing mod!

### Images

![eeh](https://github.com/BVengo/simple-shulker-preview/assets/93742413/99d9a1d2-bd6a-4001-a897-24f3565b0716)

### Fabric Version

1.20.1

**Comment by BVengo** [comment]
Thanks for the feedback, and I'm glad you're loving the mod!

I haven't implemented this feature at present since it requires writing up code specifically for the server - i.e. the server must communicate nearby shulker contents to the client such that it can be displayed. _However_, it's definitely something I would absolutely love to see implemented at some point in the future.

(Notes for self and others interested):
I haven't touched on server-side code, but ideally the implementation would allow the current client-side only functionality to remain whilst providing support for world previews if the mod is also installed on the server.

I'll keep this issue open and label it as 'Help Wanted' for now, because unfortunately I won't have enough time to look into it for a while!

**Comment by AdamRaichu** [comment]
> Thanks for the feedback, and I'm glad you're loving the mod!
> 
> I haven't implemented this feature at present since it requires writing up code specifically for the server - i.e. the server must communicate nearby shulker contents to the client such that it can be displayed. _However_, it's definitely something I would absolutely love to see implemented at some point in the future.
> 
> (Notes for self and others interested): I haven't touched on server-side code, but ideally the implementation would allow the current client-side only functionality to remain whilst providing support for world previews if the mod is also installed on the server.
> 
> I'll keep this issue open and label it as 'Help Wanted' for now, because unfortunately I won't have enough time to look into it for a while!

When you put help wanted on here, would you want this to be implemented as part of this mod, or another mod, or perhaps an optional server-side version? 

This also seems slightly out of scope for a **simple** shulker preview.

**Comment by BVengo** [comment]
Ideally part of the same mod for the sake of simplifying development. The display would be a toggleable option like everything else.

I do have regrets around including 'simple' in the name because it's a little misleading - the idea was to have a mod that makes previewing shulkers simpler than the other mods available (i.e. no hovering in the inventory required, etc) rather that it being a very barebones mod. At this stage there are enough configs for it to definitely not be simple!
Although not relevant to this particular issue, I'm certainly happy to hear feedback / suggestions for renaming the mod to be more unique and consistent yet still functionally recognisable.

**Comment by AdamRaichu** [comment]
I will do some tooling around to see if I can get something working. You can track my progress on this branch of my fork.

https://github.com/AdamRaichu/simple-shulker-preview/tree/placed-shulker-preview

**Comment by BVengo** [comment]
Brilliant, thanks heaps for that.

**Comment by BVengo** [comment]
I'm going to close this for now, as it _is_ a little outside the scope of the current mod and my availability is quite low. When I get some free time I may look into this again :)
