### ISSUE TITLE
[Feature]: Compatibility for bigger Shulkers

### ISSUE THREAD

**Issue by sternschnaube** [BVengo/simple-shulker-preview#33]
### Request Description

Carpet AMS Addition has a feature to double the Shulker size.
But the overlay isn't compatible with it.

https://github.com/Minecraft-AMS/Carpet-AMS-Addition

### Images

![image](https://github.com/BVengo/simple-shulker-preview/assets/120551916/6db515d4-03ef-47a1-ac14-7fb975c96ce1)

The progess bar doesn't scale with the bigger size. 
![image](https://github.com/BVengo/simple-shulker-preview/assets/120551916/e22d884d-b59d-4bc5-a8e3-0a8e6c3efc9c)

### Fabric Version

0.15.11

**Comment by BVengo** [comment]
Thanks for this. I'll have to look into it and see how they modify the stack size - hopefully it's in an easily compatible way!

**Comment by sternschnaube** [comment]
Thank you 😊

**Comment by BVengo** [comment]
I was looking into this for 1.21, but unfortunately I would need to implement a hard an inefficient work around for the mod you mentioned. I've opened an issue in their repo which allows for an easy compatibility fix though.

I'll leave this issue open for now - hopefully we can get this working!

**Comment by wendavid552** [comment]
> I was looking into this for 1.21, but unfortunately I would need to implement a hard an inefficient work around for the mod you mentioned. I've opened an issue in their repo which allows for an easy compatibility fix though, so we'll see how it goes.
> 
> I'll leave this issue open for now - hopefully we can get this working! 1.21 will be released without it though, since my release is already quite late.

One of a possible but inefficient method could be calculate the capacity through `.stream()` instead of `.iterateNonEmpty()` as this would go through all the slots, including the empty ones [here](https://github.com/BVengo/simple-shulker-preview/blob/fccf5f2c924ef8f8cd1e6de318fab04c2733d47e/src/main/java/com/bvengo/simpleshulkerpreview/container/ContainerManager.java#L103) (btw I haven't tested it).

**Comment by BVengo** [comment]
Yep, I tested that but, strangely, it still only returned non-empty. I suspect there are two different shulker inventories - one for the held item, which only knows the exact contents (what we're handling), and one for the block itself which has the maximum count (which their mod alters).

Their solution involved changing the size() function, but that's per-instance rather than for all shulkers. My hacky solution would be to create a temporary instance and call size(), but this would be super inefficient and have to be done every single tick in case the setting is changed between large and small at some stage.

Ideally, they just update the publically accessible MAX_SIZE variable (or whatever its called) as well for compatibility with other mods.

**Comment by sternschnaube** [comment]
Thank you both for your efforts 😊

**Comment by wendavid552** [comment]
> Yep, I tested that but, strangely, it still only returned non-empty. I suspect there are two different shulker inventories - one for the held item ContainerComponent which only knows the exact contents (what we're handling), and one for the block itself which has the maximum count (which their mod alters).
> 
> Their solution involved changing the `size()` function, but that's per-instance rather than for all shulkers. My hacky solution would be to create a temporary instance and call `size()`, but this would be super inefficient and have to be done every single tick in case the setting is changed between large and small at some stage.
> 
> Ideally, they just update the public static `INVENTORY_SIZE` variable (or whatever it was called) alongside their other changes for compatibility with other mods.

XD I am one of the contributor from Carpet-AMS-Addition😊.

The problem is, our mod is a serverside mod, while simple-shulker-preview is a clientside mod, modifying the constant serverside won't help.

**Comment by BVengo** [comment]
> XD I am one of the contributor from Carpet-AMS-Addition😊.
> 
> The problem is, our mod is a serverside mod, while simple-shulker-preview is a clientside mod, modifying the constant serverside won't help.

Oh dang, I never considered that. That puts a spanner in the works!

Will have to see if I can somehow get to the size() function from the objects I have available, because I'd really like to avoid my hacky solution.

Alternatively, I could add a custom config for shulker size modification. Not difficult to do, but I'd like to keep it as generic as possible so I don't like that solution either.

**Comment by wendavid552** [comment]
> > XD I am one of the contributor from Carpet-AMS-Addition😊.
> > The problem is, our mod is a serverside mod, while simple-shulker-preview is a clientside mod, modifying the constant serverside won't help.
> 
> Oh dang, I never considered that. That puts a spanner in the works!
> 
> Will have to see if I can somehow get to the size() function from the objects I have available, because I'd really like to avoid my hacky solution.
> 
> Alternatively, I could add a custom config for shulker size modification. Not difficult to do, but I'd like to keep it as generic as possible so I don't like that solution either.

Hi I wrote a quick fix in #35 by `.stream()`. It works actually.

**Comment by BVengo** [comment]
Thanks for that. Did some more testing and added discussion to the PR. Unfortunately I'm still not seeing `.stream()` work!

**Comment by sternschnaube** [comment]
Any update on this @BVengo? 😊

**Comment by BVengo** [comment]
Unfortunately not, sorry about that. Life has kept me too busy for non-update development recently.

It's top on my list for bug fixes though, when I'm available again!

**Comment by sternschnaube** [comment]
Thanks for letting me know 😄

**Comment by BVengo** [comment]
I've put a lot of time into investigating this and I'm afraid there's really no way to dynamically handle this until Carpet-AMS-Addition adds a method of communicating with client-side mods. See https://github.com/Minecraft-AMS/Carpet-AMS-Addition/issues/130 for their progress on this.

From a client-side perspective, the inventory simply stores a list of items on the player but does _not_ save the size of the container. The size is handled on the server-side, so client-side mods are stuck assuming that it's 27 stacks as per the vanilla size.

As a workaround, I've now implemented two new options under the Compatibility section allowing you to tell the mod what the size of your shulker boxes really are. There are two downsides to this though.
1. It effects _all_ shulker boxes - because of the server/client-side communications listed above, there is no way to dynamically adapt for shulker boxes of varying sizes
2. This mod is designed to be a QoL that feature that you set and forget, so configs are per-instance rather than per-server. If you swap between servers with and without the larger shulkers, you'll find yourself needing to change these settings regularly.

This is being implemented from 1.21.3 onwards. Unfortunately I'm rather pressed for time recently, so I may not get a chance to backdate these features.
