### ISSUE TITLE
[Feature]: configure icon transform

### ISSUE THREAD

**Issue by supersaiyansubtlety** [BVengo/simple-shulker-preview#4]
### Request Description

Could you please add options to configure the scale and offset of the preview item icon?

**Comment by BVengo** [comment]
I wondered if somebody would request this :)
I'll be looking into it for the next release because it should be simple enough, but it probably won't be implemented as rapidly as my previous releases (thanks to a busy life).

**Comment by BVengo** [comment]
All added! You'll have a little fun going back and forth trying to get the values you want, but shoot me a message with some images if you find better values :) It took me a while to settle on the current ones!

Note that the z-offset is used to make it display on top or below of other things. It is currently set at the same height as the item count (on stackable items) so that hopefully there will be minimal issues with anything else dependent on the z axis. For example, setting this value too low will make it render behind the shulker, and setting it too high will make it render above tooltips.
